[project]
name = "project-north"
version = "0.1.0"
description = "An open-source numerology research engine."
requires-python = ">=3.12"

authors = [
    { name = "Benjamin Lebrun" }
]

license = { text = "MIT" }

readme = "README.md"

keywords = [
    "numerology",
    "research",
    "python",
    "open-source"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]


[tool.ruff]
exclude = [
    "research/**"
]